name: home_decor
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  intl: ^0.20.2
  flutter_native_splash: ^2.4.6
  icons_launcher: ^3.0.0
  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  shared_preferences: ^2.5.3
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  json_serializable: ^6.9.3
  json_annotation: ^4.9.0
  build_runner: ^2.4.14
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  lottie: ^3.3.1
  zoom_tap_animation: ^1.1.0
  equatable: ^2.0.7
  shimmer: ^3.0.0
  shimmer_animation: ^2.2.2
  

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600

    - family: LeagueSpartan
      fonts:
        - asset: assets/fonts/League_Spartan/LeagueSpartan-Light.ttf
          weight: 300
        - asset: assets/fonts/League_Spartan/LeagueSpartan-Regular.ttf
          weight: 400
